version: '3.0'
services:
  aixblock:
    image: aixblock/workflow:latest     #ghcr.io/activepieces/activepieces:0.46.7
    container_name: aixblock
    restart: unless-stopped
    ## Enable the following line if you already use AP_EXECUTION_MODE with SANDBOXED or old activepieces, checking the breaking change documentation for more info.
    ## privileged: true
    ports:
      - '8080:80'
    depends_on:
      - postgres
      - redis
    # env_file: .env
    environment:
      ## Random Long Password (Optional for community edition)
      - API_KEY=CHANGEME_API_KEY
      ## 256 bit encryption key, 32 hex character
      - ENCRYPTION_KEY=CHANGEME_ENCRYPTION_KEY
      ## JWT Secret
      - JWT_SECRET=CHANGEME_JWT_SECRET
      ## It's advisable to consult the documentation and use the tools/deploy.sh to generate the passwords, keys, instead of manually filling them.
      - AP_ENGINE_EXECUTABLE_PATH=dist/packages/engine/main.js

      ## Random Long Password (Optional for community edition)
      - AP_API_KEY=CHANGEME_AP_API_KEY

      ## 256 bit encryption key, 32 hex character
      - AP_ENCRYPTION_KEY=CHANGEME_AP_ENCRYPTION_KEY
      ## JWT Secret
      - AP_JWT_SECRET=CHANGEME_AP_JWT_SECRET
      - AP_EDITION=ee
      - AP_ENVIRONMENT=prod
      - AP_FRONTEND_URL=https://workflow.aixblock.io
      - AP_WEBHOOK_TIMEOUT_SECONDS=30
      - AP_TRIGGER_DEFAULT_POLL_INTERVAL=5
      - AP_POSTGRES_DATABASE=activepieces
      - AP_BLOCKS_SOURCE=DB
      - AP_BLOCKS_SYNC_MODE=OFFICIAL_AUTO
      - AP_POSTGRES_HOST=postgres
      - AP_POSTGRES_PORT=5432
      - AP_POSTGRES_USERNAME=postgres
      - AP_POSTGRES_PASSWORD=CHANGEME_PASSWORD
      - AP_EXECUTION_MODE=UNSANDBOXED    #UNSANDBOXED
      - AP_REDIS_HOST=redis
      - AP_REDIS_PORT=6379
      - AP_FLOW_TIMEOUT_SECONDS=1600
      - AP_TELEMETRY_ENABLED=true
      - AP_SHOW_CHANGELOG=false
      - AP_TEMPLATES_SOURCE_URL="https://cloud.activepieces.com/api/v1/flow-templates"
      - AP_GOOGLE_CLIENT_ID=CHANGEME_GOOGLE_CLIENT_ID
      - AP_GOOGLE_CLIENT_SECRET=CHANGEME_GOOGLE_CLIENT_SECRET
      - AP_AIXBLOCK_CLIENT_ID=CHANGEME_AIXBLOCK_CLIENT_ID
      - AP_AIXBLOCK_CLIENT_SECRET=CHANGEME_AIXBLOCK_CLIENT_SECRET
      - AP_AIXBLOCK_PLATFORM_URI=https://app.aixblock.io
      - CRAWLEE_DISABLE_MEMORY_USAGE_LOGGING=1

    volumes:
      - ./cache:/usr/src/app/cache
    networks:
      - aixblock
  postgres:
    image: 'postgres:14.4'
    container_name: postgres
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=activepieces'
      - 'POSTGRES_PASSWORD=CHANGEME_PASSWORD'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aixblock
  redis:
    image: 'redis:7.0.7'
    container_name: redis
    restart: unless-stopped
    volumes:
      - 'redis_data:/data'
    networks:
      - aixblock
volumes:
  postgres_data:
  redis_data:
networks:
  aixblock: